### ISSUE TITLE
Let's make a bar chart on Android

### ISSUE THREAD

**Issue by gzoritchak** [data2viz/data2viz-docs#1]

**Comment by xal** [comment]
I started working on the Android version of bar chart and didn't found that Maven doesn't contain

> d2v-data2viz-android

In your JFX version, you used [d2v-data2viz-jfx](https://mvnrepository.com/artifact/io.data2viz/d2v-data2viz-jfx) artifact.
 I tried to combine 

> [d2v-data2viz-jfx](https://mvnrepository.com/artifact/io.data2viz/d2v-data2viz-jfx)
> [d2v-viz-android](https://mvnrepository.com/artifact/io.data2viz/d2v-viz-android)

But Android [d2v-viz-android](https://mvnrepository.com/artifact/io.data2viz/d2v-viz-android) doesn't have AndroidCanvaseRenderer
I can put information in the tutorial about cloning data2viz repository and using source code, but I think we should make a tutorial with library from maven
@gzoritchak Could you push android artifact? Maybe I should explore more and push myself?

**Comment by molearczyk** [comment]
I'm not sure if it's the same case(or if it's still valid), but I found out that to use the Android versions of d2v-viz dependencies, I had to fetch them explicitly as _aar_. So, for instance, to get the d2v-viz-android dependency working, I used the following declaration:
`implementation 'io.data2viz:d2v-viz-android:0.7.1@aar'

**Comment by gzoritchak** [comment]
Dependencies should use specific modules:
viz-android
core-jvm
color-jvm
...
